IF p2 THEN p4; // Useless/redundant dependency, but valid
IF p1 THEN (p3==true OR (NOT p3)) AND NOT p7 AND p9=='fixed string';
Or(p1, p3, p5 AND p7, p9 AND p1);
NOT Or(p1==true, p2==true, p3==false);
NOT AllOrNone(p7 AND p9, p8=='something', p5 AND p10=='example');
AllOrNone(p1, p5);
NOT ZeroOrOne(p1, p5, p7, p2==false, p6=='example');
ZeroOrOne(p1, p3);
AllOrNone(p6!=p8, p8==p10);
ZeroOrOne(OnlyOne(p5==false, p4==true), OnlyOne(p4, p4==true), OnlyOne(p4==true, p6));